name: PR Body Validation

on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Your PR doesn't appear to link to an AppFrame ticket! Please provide a link or create a ticket using the Atlas Request workflow in #eng-atlas.'
            })