name: PR Validation

on:
  pull_request:
    types: [opened]

jobs:
  check-request:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ always() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Looks like you forgot to link to your Atlas request ticket. If you don\'t have one, please use the Atlas Request workflow in the #eng-atlas channel.'
            })