name: PR Body Validation

on: pull_request_target

jobs:
  comment:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.pull_request.title, 'PR - ')"
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'PR doesn't meet requirements'
            })